services:
    postgis:
        image: postgis/postgis:16-3.4
        container_name: lifemap-postgis
        restart: always
        env_file:
            - path: .env
              required: true
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWD}
            - POSTGRES_DB=${PG_DB}
        volumes:
            - postgis_data:/var/lib/postgresql/data
            - ./postgis/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - 5432:5432
        command: -c config_file=/etc/postgresql/postgresql.conf
    solr:
        image: lifemap_solr
        container_name: lifemap-solr
        build:
            context: ./solr
        env_file:
            - path: .env
              required: true
        environment:
            - SOLR_AUTH_TYPE=basic
            - SOLR_AUTHENTICATION_OPTS=-Dbasicauth=solr:${SOLR_PASSWD}
        volumes:
            - solr_data:/var/solr/data
        ports:
            - 8983:8983
    mod_tile:
        image: lifemap_mod_tile
        container_name: lifemap-mod_tile
        build:
            context: ./mod_tile_deepzoom
        ports:
            - 8888:80
        volumes:
            - $HOME/builder_results:/opt/build_results
        depends_on:
            - postgis
    bbox:
        container_name: lifemap-bbox
        image: sourcepole/bbox-server-qgis
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./bbox/assets:/var/www/assets:ro
            - ./bbox/data:/opt/data
            - ./bbox/bbox.toml:/var/www/bbox.toml:ro
        depends_on:
            - postgis

volumes:
    solr_data:
    postgis_data:
