---
- name: Base server install
  hosts: lifemap-back

  tasks:
      - name: Run initial setup tasks
        ansible.builtin.import_tasks:
            file: ../common/install.yml

      - name: Add Ubuntu Docker GPG apt Key
        become: true
        ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        when: ansible_facts['distribution'] == "Ubuntu"

      - name: Add Ubuntu Docker Repository
        become: true
        ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu jammy stable
            state: present
        when: ansible_facts['distribution'] == "Ubuntu"

      - name: Update apt and install docker-ce
        become: true
        ansible.builtin.apt:
            name:
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-buildx-plugin
                - docker-compose-plugin
            update_cache: true

      - name: Add user to docker group
        become: true
        ansible.builtin.command:
            cmd: adduser {{ ansible_user }} docker
        changed_when: true

      - name: Create Caddy sites.d directory
        become: true
        ansible.builtin.file:
            path: /etc/caddy/sites.d
            state: directory
            mode: "0755"

      - name: Copy Caddy config
        become: true
        ansible.builtin.template:
            src: templates/Caddyfile.j2
            dest: /etc/caddy/sites.d/lifemap_back
            mode: preserve
            force: true

      - name: Reload Caddy
        become: true
        ansible.builtin.service:
            name: caddy
            state: reloaded

      - name: Add user to Caddy group
        become: true
        ansible.builtin.user:
            name: "{{ ansible_user }}"
            append: true
            groups: caddy

      - name: Create /var/www/lifemap_back
        become: true
        ansible.builtin.file:
            path: "{{ static_root_dir }}"
            state: directory
            mode: "0775"
            owner: caddy
            group: caddy

      - name: Create ~/back
        ansible.builtin.file:
            path: "{{ docker_dir }}"
            state: directory
