services:
    postgis:
        image: postgis/postgis:16-3.4
        container_name: lifemap-postgis
        restart: unless-stopped
        env_file:
            - path: .env
              required: true
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWD}
            - POSTGRES_DB=${PG_DB}
        volumes:
            - postgis_data:/var/lib/postgresql/data
            - ./postgis/postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - 127.0.0.1:5432:5432
        command: -c config_file=/etc/postgresql/postgresql.conf
    solr:
        image: lifemap_solr
        container_name: lifemap-solr
        restart: unless-stopped
        build:
            context: ./solr
        env_file:
            - path: .env
              required: true
        environment:
            - SOLR_AUTH_TYPE=basic
            - SOLR_AUTHENTICATION_OPTS=-Dbasicauth=solr:${SOLR_PASSWD}
        volumes:
            - solr_data:/var/solr/data
    mod_tile:
        image: lifemap_mod_tile
        container_name: lifemap-mod_tile
        restart: unless-stopped
        build:
            context: ./mod_tile_deepzoom
        env_file:
            - path: .env
              required: true
        volumes:
            - ../builder_results:/opt/build_results
        depends_on:
            - postgis
    bbox:
        container_name: lifemap-bbox
        image: sourcepole/bbox-server-qgis
        restart: unless-stopped
        env_file:
            - path: .env
              required: true
        volumes:
            - ./bbox/assets:/var/www/assets:ro
            - ./bbox/bbox.toml:/var/www/bbox.toml:ro
        depends_on:
            - postgis
    caddy:
        container_name: lifemap-caddy
        image: caddy:2
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
            - ../www/static:/static
            - ../www/front:/front

volumes:
    solr_data:
    postgis_data:
    caddy_data:
    caddy_config:
