---
- name: Lifemap builder install
  hosts: lifemap-back

  tasks:
      - name: Rsync builder
        ansible.posix.synchronize:
            src: "../builder/"
            dest: "{{ builder_dir }}"

      - name: Copy env to builder repo
        ansible.builtin.template:
            src: templates/env.j2
            dest: "{{ builder_dir }}/.env"
            mode: "0600"
            force: true

      - name: Create results directory if needed
        ansible.builtin.file:
            path: "{{ build_results_dir }}"
            state: directory
            owner: "{{ ansible_user }}"
            mode: "0755"

      - name: Apt update
        become: true
        ansible.builtin.apt:
            cache_valid_time: 3600
            update_cache: true

      - name: Install apt packages for builder
        become: true
        ansible.builtin.apt:
            name:
                - python3-pip
                - r-base-core
                - r-cran-jsonlite
                - unzip
                - curl
            state: present

      - name: Install R arrow package
        become: true
        ansible.builtin.shell:
            cmd: Rscript -e 'options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste (getRversion(), R.version["platform"], R.version["arch"], R.version["os"]))); install.packages("arrow", repos = "https://packagemanager.rstudio.com/all/__linux__/noble/latest")'
            executable: /bin/bash

      - name: Install uv with pip
        ansible.builtin.shell:
            cmd: python3 -m pip install --break-system-packages uv
            executable: /bin/bash
        changed_when: true

      - name: Install python and python packages for builder
        ansible.builtin.command:
            chdir: "{{ builder_dir }}"
            cmd: ~/.local/bin/uv sync
            # executable: /bin/bash
        changed_when: true

      - name: Rsync taxo
        ansible.posix.synchronize:
            src: ../builder/taxo/
            dest: "{{ build_results_dir }}/taxo/"

      - name: Creates lifemap update cron
        become: true
        ansible.builtin.cron:
            name: "lifemap update"
            # Monday at 2AM
            weekday: "1"
            minute: "0"
            hour: "2"
            user: "{{ ansible_user }}"
            job: ". /home/{{ ansible_user }}/.profile && cd {{ builder_dir }} && ./cron_update.sh"
            cron_file: lifemap_update
