---
- name: Server config update
  hosts: lifemap-back

  tasks:
      - name: Copy Caddy config
        become: true
        ansible.builtin.template:
            src: templates/Caddyfile.j2
            dest: /etc/caddy/sites.d/lifemap_back
            mode: preserve
            force: true

      - name: Reload Caddy
        become: true
        ansible.builtin.service:
            name: caddy
            state: reloaded

      - name: Pull builder repo # noqa: latest
        ansible.builtin.git:
            repo: "{{ builder_git_url }}"
            dest: "/home/{{ ansible_user }}/builder"
            force: true

      - name: Stop containers
        ansible.builtin.command:
            chdir: "{{ docker_dir }}"
            cmd: docker compose down
        changed_when: true

      # - name: Update containers
      #   ansible.builtin.command:
      #       chdir: "{{ docker_dir }}"
      #       cmd: docker compose pull
      #   changed_when: true

      - name: Restart containers
        ansible.builtin.command:
            chdir: "{{ docker_dir }}"
            cmd: docker compose up -d --build
        changed_when: true
