[project]
name = "lifemap-builder"
version = "0.1.0"
description = "Lifemap backend data builder"
readme = "README.md"
requires-python = ">= 3.14"
authors = [{ name = "Damien de Vienne", email = "damien.de-vienne@univ-lyon1.fr" }]
dependencies = [
  "ete4>=4.4.0",
  "numpy>=1.26.4",
  "polars>=1.37.1",
  "psycopg[binary]>=3.1.19",
  "python-dotenv>=1.2.2",
  "requests>=2.34.2",
  "six>=1.16.0",
  "tqdm>=4.66.4",
]

[dependency-groups]
dev = [
  "ruff>=0.15.9",
  "ty>=0.0.29",
]

[tool.ruff]
extend-exclude = ["notebooks"]
target-version = "py310"
line-length = 88
lint.select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
lint.ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105",
  "S106",
  "S107",
  # Ignore complexity
  "C901",
  "PLR0911",
  "PLR0912",
  "PLR0913",
  "PLR0915",
]
lint.unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 110

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ty.environment]
root = ["./tree"]
python-version = "3.14"

[tool.uv]
package = false
